spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JayPatel-15/hotel-rating-system-config-server.git
          search-paths: '*'

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka

server:
  port: 8071