spring:
  application:
    name: user-service

  config:
    import: configserver:http://localhost:8071/

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        sliding-window-type: count_based
        sliding-window-size: 100
        failure-rate-threshold: 40
        wait-duration-in-open-state: 200s
        permitted-number-of-calls-in-half-open-state: 10
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info